In [5]:
import numpy as np

# Define matrices A, B, C (example 2x2 matrices)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

# Define vectors r_left and r_right (example 3-dimensional vectors)
r_left = np.array([1, 0, -1])
r_right = np.array([2, -2, 3])

# Compute the Kronecker products
kron_A_rleft = np.kron(A, r_left)
kron_A_rright = np.kron(A, r_right)
kron_B_rleft = np.kron(B, r_left)
kron_C_rright = np.kron(C, r_right)

# Combine according to the given expression
result = (0.7 * kron_A_rleft + 0.4 * kron_A_rright +
          0.2 * kron_B_rleft - 0.9 * kron_C_rright)

print(result)

[[-13.7  15.4 -24.8 -13.8  16.4 -27.2]
 [-13.9  17.4 -29.6 -14.   18.4 -32. ]]


In [1]:
import numpy as np
import pandas as pd

def generate_dummy_data(csv_file, num_samples=100):
    """
    Generate a dummy dataset and save it to a CSV file.
    """
    r_left = np.random.rand(num_samples, 3)
    r_right = np.random.rand(num_samples, 3)
    targets = np.random.rand(num_samples, 3)
    
    data = np.hstack((r_left, r_right, targets))
    columns = [f"r_left_{i}" for i in range(3)] + [f"r_right_{i}" for i in range(3)] + [f"target_{i}" for i in range(3)]
    df = pd.DataFrame(data, columns=columns)
    df.to_csv(csv_file, index=False)

def load_data(csv_file):
    """
    Load data from a CSV file.
    """
    data = pd.read_csv(csv_file)
    r_left = data.iloc[:, :3].values  # First 3 columns are r_left
    r_right = data.iloc[:, 3:6].values  # Next 3 columns are r_right
    targets = data.iloc[:, 6:].values  # Remaining columns are targets
    return r_left, r_right, targets

def neural_layer(A, B, C, r_left, r_right):
    """
    Compute the output based on the given formula.
    """
    term1 = 0.7 * np.dot(r_left, A.T)  # Matrix multiplication
    term2 = 0.4 * np.dot(r_right, A.T)
    term3 = 0.2 * np.dot(r_left, B.T)
    term4 = -0.9 * np.dot(r_right, C.T)
    
    output = term1 + term2 + term3 + term4
    return output

def mean_squared_error(predictions, targets):
    """
    Compute the mean squared error loss.
    """
    return np.mean((predictions - targets) ** 2)

def train_model(A, B, C, r_left, r_right, targets, learning_rate=0.01, epochs=1000):
    """
    Train the model using gradient descent.
    """
    for epoch in range(epochs):
        output = neural_layer(A, B, C, r_left, r_right)
        loss = mean_squared_error(output, targets)
        
        error = output - targets
        
        # Compute gradients
        grad_A = 0.7 * np.dot(error.T, r_left) + 0.4 * np.dot(error.T, r_right)
        grad_B = 0.2 * np.dot(error.T, r_left)
        grad_C = -0.9 * np.dot(error.T, r_right)
        
        # Update weights
        A -= learning_rate * grad_A
        B -= learning_rate * grad_B
        C -= learning_rate * grad_C
        
        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
    
    return A, B, C

# Generate and load dummy data
csv_file = "dummy_data.csv"
generate_dummy_data(csv_file)
r_left, r_right, targets = load_data(csv_file)

# Initialize weights
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = np.random.rand(3, 3)

# Train the model
A, B, C = train_model(A, B, C, r_left, r_right, targets)
print(A, B, C)


Epoch 0, Loss: 0.4496
Epoch 100, Loss: 0.0882
Epoch 200, Loss: 0.0880
Epoch 300, Loss: 0.0880
Epoch 400, Loss: 0.0880
Epoch 500, Loss: 0.0880
Epoch 600, Loss: 0.0880
Epoch 700, Loss: 0.0880
Epoch 800, Loss: 0.0880
Epoch 900, Loss: 0.0880
[[ 0.01709714  0.30238564 -0.22541287]
 [ 0.16231905  0.12806729 -0.09889405]
 [ 0.3088229   0.08402548  0.10988065]] [[ 0.33883426  0.04219613  0.55478878]
 [-0.24050283 -0.09667679  0.58190136]
 [ 0.0173181   0.68098806 -0.14339826]] [[-0.16754943 -0.19984807 -0.3025727 ]
 [-0.38942973 -0.13382882 -0.25536531]
 [ 0.03717029 -0.19384111 -0.08223671]]
